# Generated by Django 5.1.4 on 2025-05-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('injured', models.PositiveIntegerField(default=0)),
                ('fatalities', models.PositiveIntegerField(default=0)),
                ('coordinates_lat', models.FloatField()),
                ('coordinates_lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accident',
                'verbose_name_plural': 'Accidents',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
