# Generated by Django 5.1.4 on 2025-06-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
