# Generated by Django 5.2.2 on 2025-06-06 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_driver_options_driver_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('response_time', models.CharField(blank=True, max_length=20, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.alert')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_history', to='api.driver')),
            ],
            options={
                'verbose_name': 'Alert History',
                'verbose_name_plural': 'Alert Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('status_change', models.CharField(blank=True, max_length=100, null=True)),
                ('response_time', models.CharField(blank=True, max_length=20, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_history', to='api.alert')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.driver')),
            ],
            options={
                'verbose_name': 'Driver History',
                'verbose_name_plural': 'Driver Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
