# Generated by Django 5.2.2 on 2025-06-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_driver_created_at_alerthistory_driverhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('complete', 'Complete'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
