# Generated by Django 5.2.2 on 2025-06-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_alert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='accident_clip',
            field=models.FileField(blank=True, null=True, upload_to='accident_clips/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
