# Generated by Django 5.1.4 on 2025-05-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=10, unique=True)),
                ('time', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('complete', 'Complete'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('response_time', models.CharField(blank=True, max_length=20, null=True)),
                ('coordinates_lat', models.FloatField()),
                ('coordinates_lng', models.FloatField()),
                ('accident_clip', models.FileField(blank=True, null=True, upload_to='accident_clips/')),
                ('time_remaining', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='drivers_app.driver')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
