# Generated by Django 5.2.2 on 2025-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
