# Generated by Django 5.2.2 on 2025-06-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_app', '0002_alert_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_ai_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(default='Accident Emergency', max_length=50),
        ),
    ]
